"""Persistence for ApiPay invoices (table `apipay_invoices`, migrations 037-039).

One row per bookings/batch request that carried a chargeable avans, written
inside the same transaction that inserts the bookings — so an invoice can never
reference bookings that were rolled back, nor bookings exist without a record
of what they were charged.

The row is committed BEFORE ApiPay is called (status 'created', invoice_id
NULL) and sending is a separate retryable step, which is why `external_order_id`
— generated by us, known before the call — is the identity the webhook resolves
against. `invoice_id` is ApiPay's own id and may still be NULL when their first
webhook lands. See migration 039.
"""

import logging

import psycopg2.extras

from integrations.apipay_client import (
    OPEN_STATUSES,
    STATUS_CANCELLED,
    STATUS_CREATED,
    STATUS_PAID,
)
from integrations.repo.utils import _conn

logger = logging.getLogger(__name__)

# How long a claimed-but-unsent row is left alone before another worker may
# retry it. Longer than APIPAY_TIMEOUT so a send still in flight is not
# duplicated; short enough that a crashed worker's rows resume quickly.
_SEND_LEASE_SECONDS = 60


def insert_invoice(cur, external_order_id: str, phone: str, amount,
                   booking_ids: list[int], source: str = "manager",
                   notify_chat_id: str | None = None,
                   notify_provider: str | None = None,
                   notify_lang: str | None = None) -> int:
    """Queue an invoice on the caller's cursor; returns its local id.

    Writes the row only — ApiPay is NOT called here. The caller commits this
    alongside its bookings, then hands the row to `apipay_service.send_invoice`.
    `notify_*` carry who to message when it is paid (bot flow); NULL for
    manager-created invoices, which are reported in the manager UI instead.
    """
    cur.execute(
        "INSERT INTO apipay_invoices (external_order_id, phone, amount, booking_ids, "
        "  status, source, notify_chat_id, notify_provider, notify_lang) "
        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING id",
        (external_order_id, phone, amount, list(booking_ids), STATUS_CREATED,
         source, notify_chat_id, notify_provider, notify_lang),
    )
    return cur.fetchone()["id"]


def attach_invoice_id(cur, row_id: int, invoice_id: int, status: str) -> None:
    """Store the id ApiPay assigned, once the API call has succeeded."""
    cur.execute(
        "UPDATE apipay_invoices SET invoice_id = %s, status = %s, "
        "  last_send_error = NULL, updated_at = NOW() "
        "WHERE id = %s",
        (int(invoice_id), status, row_id),
    )


def mark_sent(row_id: int, invoice_id: int, status: str) -> None:
    """Committed form of `attach_invoice_id` — the outbox's second step."""
    with _conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE apipay_invoices SET invoice_id = %s, status = %s, "
                "  last_send_error = NULL, updated_at = NOW() "
                "WHERE id = %s",
                (int(invoice_id), status, int(row_id)),
            )


def mark_send_failed(row_id: int, error: str) -> None:
    """Record why a send failed. The row stays in the outbox for a retry."""
    with _conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE apipay_invoices SET last_send_error = %s, updated_at = NOW() "
                "WHERE id = %s",
                (error[:500], int(row_id)),
            )


def claim_pending_sends(limit: int = 20, max_attempts: int = 10) -> list[dict]:
    """Take up to `limit` unsent invoices, leasing them against other workers.

    The scheduler runs in every gunicorn worker, so two processes can sweep at
    once. `FOR UPDATE SKIP LOCKED` keeps them off the same rows inside the
    transaction, and bumping `updated_at` leases each row for
    `_SEND_LEASE_SECONDS` afterwards — long enough that a send still in flight
    is not started again elsewhere.

    Rows past `max_attempts` are left behind rather than retried forever; they
    stay visible in the table with `last_send_error` set.
    """
    with _conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT * FROM apipay_invoices "
                " WHERE invoice_id IS NULL AND status = %s "
                "   AND send_attempts < %s "
                "   AND updated_at < NOW() - make_interval(secs => %s) "
                " ORDER BY created_at "
                " LIMIT %s FOR UPDATE SKIP LOCKED",
                (STATUS_CREATED, max_attempts, _SEND_LEASE_SECONDS, limit),
            )
            rows = [dict(r) for r in cur.fetchall()]
            if rows:
                cur.execute(
                    "UPDATE apipay_invoices SET send_attempts = send_attempts + 1, "
                    "  updated_at = NOW() WHERE id = ANY(%s)",
                    ([r["id"] for r in rows],),
                )
    return rows


def reprice_pending(row_id: int, amount, booking_ids: list[int]) -> bool:
    """Re-cut an unsent row to the bookings that are still awaiting payment.

    A batch invoice is queued for what existed at the time; by the time a
    retried send goes out, some of those bookings may be gone. ApiPay is told
    an amount exactly once, so it has to be the amount of what survives — and
    `booking_ids` has to match it, since the webhook settles the payment across
    that column and would otherwise split money over a booking we did not bill.

    Returns False when the row is no longer sendable — cancelled while the
    sweeper held it, or already sent. That is the last check before the client
    is asked for money, and the guard the `WHERE` clause exists for: the
    cancellation paths commit the booking change first and retire the invoice
    a moment later, so a sweep can arrive in between.
    """
    with _conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE apipay_invoices SET amount = %s, booking_ids = %s, "
                "  updated_at = NOW() "
                " WHERE id = %s AND status = %s AND invoice_id IS NULL",
                (amount, list(booking_ids), int(row_id), STATUS_CREATED),
            )
            return cur.rowcount > 0


def cancel_unsent_for_bookings(booking_ids: list[int], reason: str) -> list[int]:
    """Retire queued-but-unsent invoices whose bookings are gone.

    Without this the outbox would happily send an invoice for a slot the TTL
    sweeper has already released — asking a client to pay for nothing.
    """
    if not booking_ids:
        return []
    with _conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "UPDATE apipay_invoices SET status = %s, error_message = %s, "
                "  updated_at = NOW() "
                " WHERE invoice_id IS NULL AND status = %s AND booking_ids && %s "
                " RETURNING id",
                (STATUS_CANCELLED, reason, STATUS_CREATED, list(booking_ids)),
            )
            return [r["id"] for r in cur.fetchall()]


def cancel_unsent_row(row_id: int, reason: str) -> bool:
    """Retire one queued row so the outbox will not resurrect it.

    The sibling of `cancel_unsent_for_bookings` for when the bookings are fine
    and it is the invoice that is unwanted — the caller has already offered the
    client another way to pay, so a retry would be a second request for the
    same money.

    Guarded exactly like `reprice_pending`: if a webhook has already backfilled
    `invoice_id` (the send landed, the response did not) the row is ApiPay's
    business now, and False says so.
    """
    with _conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE apipay_invoices SET status = %s, error_message = %s, "
                "  updated_at = NOW() "
                " WHERE id = %s AND status = %s AND invoice_id IS NULL",
                (STATUS_CANCELLED, reason, int(row_id), STATUS_CREATED),
            )
            return cur.rowcount > 0


def claim_open_invoices(older_than_seconds: int, limit: int = 50,
                        max_age_days: int = 3) -> list[dict]:
    """Take sent invoices that have sat in a non-terminal status too long.

    These are the ones a lost webhook leaves behind: ApiPay knows the invoice
    was paid (or expired) and we do not. Only rows that reached ApiPay qualify
    — `invoice_id IS NOT NULL`; a still-unsent row is the outbox's business.

    `older_than_seconds` keeps normal deliveries out of it: a webhook that is
    merely a few seconds behind must not be raced. Leasing works exactly as in
    `claim_pending_sends` — SKIP LOCKED plus an `updated_at` bump — so the
    workers do not all poll the same invoice, and each row is re-checked at
    most once per window instead of on every pass.

    `max_age_days` stops us polling ApiPay forever for something that will
    never resolve; those rows stay in the table, visibly open.
    """
    with _conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT * FROM apipay_invoices "
                " WHERE invoice_id IS NOT NULL AND status = ANY(%s) "
                "   AND updated_at < NOW() - make_interval(secs => %s) "
                "   AND created_at > NOW() - make_interval(days => %s) "
                " ORDER BY updated_at "
                " LIMIT %s FOR UPDATE SKIP LOCKED",
                ([s for s in OPEN_STATUSES if s != STATUS_CREATED],
                 older_than_seconds, max_age_days, limit),
            )
            rows = [dict(r) for r in cur.fetchall()]
            if rows:
                cur.execute(
                    "UPDATE apipay_invoices SET updated_at = NOW() WHERE id = ANY(%s)",
                    ([r["id"] for r in rows],),
                )
    return rows


def get_by_invoice_id(invoice_id: int) -> dict | None:
    with _conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT * FROM apipay_invoices WHERE invoice_id = %s", (int(invoice_id),)
            )
            row = cur.fetchone()
    return dict(row) if row else None


def claim_status(cur, invoice_id: int, status: str, paid_at=None,
                 error_code: str | None = None,
                 error_message: str | None = None,
                 kaspi_invoice_id: str | None = None,
                 external_order_id: str | None = None) -> dict | None:
    """Move an invoice to `status`, returning the row only on a real transition.

    Runs on the CALLER's cursor (a RealDictCursor), and must: the claim and the
    booking-side effect it authorises have to commit together. Claiming in a
    transaction of its own leaves a window where the claim lands and the apply
    does not — every ApiPay retry then reads the status it already set, gets
    None, answers 200 duplicate, and the paid booking is never confirmed. See
    `apipay_service.apply_webhook_status`, the only caller.

    Returns None when the invoice is unknown or already in that status — which
    is how webhook redelivery (ApiPay retries up to 11 times) stays idempotent:
    only the first delivery gets a row back and does the booking-side work.
    Terminal statuses are never overwritten by a later in-flight status.

    Resolution is by `external_order_id` first: we generate it before calling
    ApiPay, so it is already committed when their webhook lands. `invoice_id`
    is only written after a successful send and can legitimately still be NULL
    at that moment — keying on it alone would drop the transition, answer 200,
    and stop the retries, stranding a paid booking in awaiting_payment.

    A webhook that arrives before the send response also backfills `invoice_id`,
    since that delivery is our first sighting of it.
    """
    row = None
    if external_order_id:
        cur.execute(
            "SELECT * FROM apipay_invoices WHERE external_order_id = %s FOR UPDATE",
            (external_order_id,),
        )
        row = cur.fetchone()
    if row is None and invoice_id is not None:
        cur.execute(
            "SELECT * FROM apipay_invoices WHERE invoice_id = %s FOR UPDATE",
            (int(invoice_id),),
        )
        row = cur.fetchone()
    if not row:
        logger.warning(
            "[APIPAY] Вебхук по неизвестному счёту id=%s external_order_id=%s",
            invoice_id, external_order_id)
        return None
    if row["status"] == status:
        return None
    if row["status"] not in OPEN_STATUSES and status in OPEN_STATUSES:
        # Late-arriving 'pending' after 'paid' — ignore, don't reopen.
        return None
    cur.execute(
        "UPDATE apipay_invoices SET status = %s, error_code = %s, "
        "  error_message = %s, paid_at = COALESCE(%s, paid_at), "
        "  kaspi_invoice_id = COALESCE(%s, kaspi_invoice_id), "
        "  invoice_id = COALESCE(invoice_id, %s), updated_at = NOW() "
        "WHERE id = %s",
        (status, error_code, error_message,
         paid_at if status == STATUS_PAID else None,
         kaspi_invoice_id,
         int(invoice_id) if invoice_id is not None else None,
         row["id"]),
    )
    # The PRE-update row: callers need the booking_ids and amount it was raised
    # for, but `kaspi_invoice_id` only arrives now — merge it in, along with an
    # `invoice_id` this delivery may have been the first to tell us.
    row = dict(row)
    row["kaspi_invoice_id"] = kaspi_invoice_id or row.get("kaspi_invoice_id")
    row["invoice_id"] = row.get("invoice_id") or invoice_id
    return row


def open_invoices_for_bookings(booking_ids: list[int]) -> list[dict]:
    """Invoices still awaiting payment that cover any of `booking_ids`.

    Used by the reservation-TTL sweeper: once the slot is released the invoice
    must be cancelled, or the client could still pay for a booking they lost.
    """
    if not booking_ids:
        return []
    with _conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT * FROM apipay_invoices "
                " WHERE status = ANY(%s) AND invoice_id IS NOT NULL "
                "   AND booking_ids && %s",
                (list(OPEN_STATUSES), list(booking_ids)),
            )
            return [dict(r) for r in cur.fetchall()]


def awaiting_payment_slots(booking_ids: list[int]) -> tuple[list[int], int]:
    """Of `booking_ids`, those still awaiting payment — and how many SLOTS they form.

    The avans is charged per slot, not per row: a day-crossing booking is two
    rows sharing one `group_transition` but only one 10 000 ₸ avans. Returns
    ``(ids, slot_count)`` so a re-issued invoice charges the same as the original.
    """
    if not booking_ids:
        return [], 0
    with _conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute(
                "SELECT id, COALESCE(group_transition::text, 'id:' || id) AS slot_key "
                "  FROM bookings WHERE id = ANY(%s) AND state = 'awaiting_payment'",
                (list(booking_ids),),
            )
            rows = cur.fetchall()
    return [r["id"] for r in rows], len({r["slot_key"] for r in rows})


def flag_manual_refund(cur, invoice_id: int, note: str) -> None:
    """Mark an invoice paid after its bookings were gone — needs a human refund.

    On the caller's cursor: this runs while the webhook transaction still holds
    `claim_status`'s FOR UPDATE lock on the very same row, so a second
    connection here would block on that lock until the statement timeout.
    """
    cur.execute(
        "UPDATE apipay_invoices SET error_code = 'paid_after_cancellation', "
        "  error_message = %s, updated_at = NOW() WHERE invoice_id = %s",
        (note, int(invoice_id)),
    )


def mark_cancelled(invoice_id: int, reason: str) -> None:
    """Record a locally-initiated cancellation (TTL sweep)."""
    with _conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "UPDATE apipay_invoices SET status = %s, error_message = %s, "
                "  updated_at = NOW() WHERE invoice_id = %s AND status = ANY(%s)",
                (STATUS_CANCELLED, reason, int(invoice_id), list(OPEN_STATUSES)),
            )
