-- Add the ТОО "КЕЛЕШЕК СПОРТ" / ФШ Допшы fiscal-receipt seller BIN as a second
-- active Kaspi recipient. Fiscal receipts carry this BIN; the legacy P2P-style
-- DOPSHY recipient stays valid alongside it.
