ALTER TABLE bookings ALTER COLUMN source TYPE VARCHAR(100);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS repeat BOOLEAN DEFAULT FALSE;
ALTER TABLE booking_events ALTER COLUMN actor_type TYPE VARCHAR(100);
